### ISSUE TITLE
LaTeK integrals with fractions inside roots do not render properly.

### ISSUE THREAD

**Issue by omgimanerd** [izuzak/atom-pdf-view#156] opened 2016-11-07 18:02 UTC
How they should look (using external pdf viewer):
![image](https://cloud.githubusercontent.com/assets/7121024/20069367/4c83d4a2-a4ea-11e6-8dd5-79137e90fd8e.png)

What it looks like when rendered inside atom:
![image](https://cloud.githubusercontent.com/assets/7121024/20069402/6761e714-a4ea-11e6-80b8-d6fe60a118ce.png)

What other information should I provide?

**Comment by izuzak** [comment] 2016-11-08 09:16
Thanks for opening an issue, @omgimanerd 👋 

> What other information should I provide?

It's always helpful to provide an example PDF which you are reproducing this with (you can attach it in a comment as an attachment). Also, sharing the Atom version you use, the version of this package you use, and the OS+version would be great as well.

**Comment by izuzak** [comment] 2016-11-08 09:17
Also wondering if this might be a duplicate of https://github.com/izuzak/atom-pdf-view/issues/131 💭

**Comment by omgimanerd** [comment] 2016-11-08 15:39
Here's a pdf where it occurred for me, in general, I was able to create this rendering bug any time I had a 
\sqrt{} inside \frac{}{} inside an \int.
[10.2_calculus-with-parametric-curves.pdf](https://github.com/izuzak/atom-pdf-view/files/578577/10.2_calculus-with-parametric-curves.pdf)

I'm using:
Ubuntu 16.04
Atom 1.9.8 with pdf-view version 0.51.0

**Comment by izuzak** [comment] 2016-11-13 14:21
Thanks. Those integrals look normal for me, on OSX, so I'm guessing this is a duplicate of #131. There's nothing in this package that touches the content of PDFs, so if they're not rendered correctly -- it's probably a problem in the underlying pdf.js library.

**Closed by izuzak** 2016-11-13 14:21 UTC
