### ISSUE TITLE
Multiple reloads on latexmk

### ISSUE THREAD

**Issue by guyhoffman** [izuzak/atom-pdf-view#166] opened 2017-01-31 17:20 UTC
Every time you compile a LaTeX file with latexmk, it results in 3-5 (slow) refreshes of the pdf-view window. Is that something that can be addressed? Thanks for your hard work!

**Comment by izuzak** [comment] 2017-02-02 08:01
Thanks for opening an issue :bow: -- this seems like a duplicate of https://github.com/izuzak/atom-pdf-view/issues/161 so I'm closing this in favor of that. :v:

**Closed by izuzak** 2017-02-02 08:01 UTC
