### ISSUE TITLE
every time rebuild the pdf file using latex, the viewer will display the first page.

### ISSUE THREAD

**Issue by X-G** [izuzak/atom-pdf-view#106] opened 2016-01-13 08:33 UTC
It should be good if the viewer will display the page before the pdf file had been rebuilt.

**Comment by izuzak** [comment] 2016-01-13 10:18
Thanks for the suggestion -- I believe this is a duplicate of https://github.com/izuzak/atom-pdf-view/issues/13, so I'm closing this in favor of that issue. :v:

**Closed by izuzak** 2016-01-13 10:18 UTC
