### ISSUE TITLE
local images are not rendered

### ISSUE THREAD

**Issue by tatoosh** [izuzak/atom-pdf-view#183] opened 2017-06-30 14:03 UTC
Images stored locally on my disc will not be rendered, see the attached image.
http://i.imgur.com/udke5Dc.jpg

**Comment by izuzak** [comment] 2017-07-01 08:06
Hi @tatoosh 👋 

Thanks for opening an issue, but a partial screenshot without any other information or an example PDF isn't really helpful in investigating problems. I'm going to close this due to lack of information, but happy to reopen if you can provide more details. Specifically:
* which version of Atom are you using and on which OS
* which version of the pdf-view package are you using
* can you attach an example PDF in a comment so that we can try and reproduce the problem and compare to other PDF viewers

Thanks!

**Closed by izuzak** 2017-07-01 08:06 UTC
